version: '3.6'

services:
  app: 
    build: 
      target: dev
    volumes: 
      - ./:/app:cached
      - /app/node_modules
    command:
      - npm
      - "run"
      - "serve" 
    environment:
      - CHOKIDAR_USEPOLLING=true